<!--==============================footer=================================-->

<footer>
		
    <div class="coordonnees">
    Alexis AMAND<br />Développement Web et SEO<br />---<br />06.62.63.79.21<br />alexis.amand@boitasite.com<br />
    </div>
    
    <div style="width:50%;float:left;margin-bottom:25px;text-align:center;font-family: Verdana, Geneva, sans-serif;font-size: 0.8em;">
    <span>Follow Moi:</span><br /><br />
    <a href="https://twitter.com/alexisamand"><i class="fi-swluxl-facebook"></i></a>
    &nbsp;<a href="https://www.facebook.com/Alexis-AMAND-Webmaster-507308975998494/"><i class="fi-swluxl-twitter"></i></a>
    </div>
    
    <div style="text-align:center;clear:both;font-size: 0.7em;">© 2016-2020 - Alexis AMAND - <a href="https://hoodspot.fr/programmeur-informatique/amand-alexis-51750123500017/"  style="font-size: 1em;">Profil Hoodspot</a></div>
			
</footer>